name: Publish version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        default: 'patch'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm version ${version}
        env:
          version: ${{ github.event.inputs.version }}
